# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugangList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField(max_length=200)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2017, 12, 9, 20, 20, 47, 148227))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2017, 12, 9, 20, 20, 47, 148245))),
                ('CreatedID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
    ]
