# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugangpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suganglist',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 9, 20, 31, 34, 951572)),
        ),
        migrations.AlterField(
            model_name='suganglist',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 9, 20, 31, 34, 951591)),
        ),
    ]
