# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '__first__'),
        ('lecture', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalCount', models.IntegerField(default=0)),
                ('WeekCount', models.IntegerField(default=0)),
                ('GLS', models.IntegerField(default=0)),
                ('ISL', models.IntegerField(default=0)),
                ('ME', models.IntegerField(default=0)),
                ('SOF', models.IntegerField(default=0)),
                ('SOCAS', models.IntegerField(default=0)),
                ('SESE', models.IntegerField(default=0)),
                ('MCE', models.IntegerField(default=0)),
                ('CCD', models.IntegerField(default=0)),
                ('LS', models.IntegerField(default=0)),
                ('CSEE', models.IntegerField(default=0)),
                ('CPSW', models.IntegerField(default=0)),
                ('ICT', models.IntegerField(default=0)),
                ('SCCE', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Course_id', models.IntegerField()),
                ('Speedy', models.PositiveSmallIntegerField(default=5)),
                ('Homework', models.PositiveSmallIntegerField(default=5)),
                ('Level_Difficulty', models.PositiveSmallIntegerField(default=5)),
                ('Check', models.BooleanField(default=False)),
                ('CourseComment', models.TextField(max_length=2000)),
                ('StarPoint', models.FloatField(default=0)),
                ('What_Answer', models.IntegerField(default=0)),
                ('Who_Answer', models.TextField(max_length=200, null=True)),
                ('Course_Answer', models.IntegerField(default=0)),
                ('Url_Answer', models.TextField(max_length=200, null=True)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2017, 12, 9, 20, 30, 31, 535119))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2017, 12, 9, 20, 30, 31, 535140))),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture')),
                ('CreatedID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Description_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.TextField(max_length=200)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture')),
                ('CreatedID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Group_Total_Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=20)),
                ('CourseName', models.CharField(max_length=80, null=True)),
                ('GroupTotalCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Total_Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Speedy', models.IntegerField(default=0)),
                ('Total_Homework', models.IntegerField(default=0)),
                ('Total_Level_Difficulty', models.IntegerField(default=0)),
                ('Total_Count', models.IntegerField(default=0)),
                ('Total_StarPoint', models.FloatField(default=0)),
                ('Total_Recommend', models.IntegerField(default=0)),
                ('Total_Mix', models.IntegerField(default=0)),
                ('Total_Short_Answer', models.IntegerField(default=0)),
                ('Total_Long_Answer', models.IntegerField(default=0)),
                ('Total_Unknown_Answer', models.IntegerField(default=0)),
                ('Total_Book_Like', models.IntegerField(default=0)),
                ('Total_Ppt_Like', models.IntegerField(default=0)),
                ('Total_Practice_Like', models.IntegerField(default=0)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture')),
            ],
        ),
        migrations.AddField(
            model_name='course_evaluation',
            name='Exam_Answer',
            field=models.ManyToManyField(to='index.Description_Answer'),
        ),
    ]
