# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_evaluation',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 9, 20, 30, 36, 136197)),
        ),
        migrations.AlterField(
            model_name='course_evaluation',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 9, 20, 30, 36, 136218)),
        ),
    ]
