# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '__first__'),
        ('index', '0002_auto_20171209_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(default=None, max_length=1000, storage=index.models.OverwriteStorage(), upload_to=index.models.upload_path_handler)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Total_Evaluation')),
                ('CreatedID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='course_evaluation',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 9, 20, 31, 9, 988092)),
        ),
        migrations.AlterField(
            model_name='course_evaluation',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 9, 20, 31, 9, 988112)),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='UserCourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Course_Evaluation'),
        ),
    ]
